name: dist
dependencies:
- ipython
- notebook
- jupyterlab
- numpy
- scipy
- pandas
- statsmodels
- dask
- pyarrow
- matplotlib
- seaborn
- plotly
- bokeh
- pydot
- scikit-learn
- lightgbm
- tensorflow
- tensorboard
- keras
- nltk
- spacy
- gensim
- scrapy
- beautifulsoup4
- pip:
    - poetry
    - ipdb
    - pyspark
    - torch
    - torchvision
    - altair
    - xgboost
    - catboost
    - eli5
